repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.3
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
    rev: v1.13.0
    hooks:
      - id: basedpyright
  - repo: https://github.com/JoC0de/pre-commit-prettier
    rev: v3.6.2
    hooks:
      - id: prettier
  - repo: https://github.com/mohsentaleb/precommit-tsc
    rev: "v1.0.0"
    hooks:
      - id: tsc
        types_or: [javascript, ts, jsx, tsx]
