services:
  web:
    build: .
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
    ports:
      - "8000:8000"
    volumes:
      - db:/etc/db
    environment:
      SAPLING_SQLITE_PATH: "/etc/db/diffswarm-dev-sapling.sqlite3"
      HOST: 0.0.0.0
volumes:
  db:
