services:
  web:
    build: .
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
    ports:
      - "8000:8000"
    volumes:
      - db:/etc/db
    environment:
      DATABASE_URL: "sqlite:////etc/db/diffswarm-dev.sqlite3"
      HOST: 0.0.0.0
volumes:
  db:
