services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - db:/etc/db
    environment:
      DATABASE_URL: "sqlite:////etc/db/diffswarm-dev.sqlite3"
      HOST: 0.0.0.0
volumes:
  db:
