"""
description.

Revision ID: 78792e4b8dbc
Revises: 8adf2048f645
Create Date: 2025-08-12 20:23:58.811336

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78792e4b8dbc"
down_revision: str | Sequence[str] | None = "8adf2048f645"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("diff", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("diff", "description")
    # ### end Alembic commands ###
