"""
initial migration.

Revision ID: 8adf2048f645
Revises:
Create Date: 2025-08-09 22:53:57.698574

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8adf2048f645"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diff",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("raw", sa.Text(), nullable=False),
        sa.Column("from_filename", sa.Text(), nullable=False),
        sa.Column("from_timestamp", sa.Text(), nullable=True),
        sa.Column("to_filename", sa.Text(), nullable=False),
        sa.Column("to_timestamp", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hunk",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("diff_id", sa.String(length=26), nullable=False),
        sa.Column("from_start", sa.Integer(), nullable=False),
        sa.Column("from_count", sa.Integer(), nullable=False),
        sa.Column("to_start", sa.Integer(), nullable=False),
        sa.Column("to_count", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["diff_id"], ["diff.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "comment",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("hunk_id", sa.String(length=26), nullable=False),
        sa.Column("diff_id", sa.String(length=26), nullable=False),
        sa.Column("line_index", sa.Integer(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("in_reply_to", sa.String(length=26), nullable=True),
        sa.ForeignKeyConstraint(["diff_id"], ["diff.id"]),
        sa.ForeignKeyConstraint(["hunk_id"], ["hunk.id"]),
        sa.ForeignKeyConstraint(["in_reply_to"], ["comment.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "line",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("hunk_id", sa.String(length=26), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("line_number_old", sa.Integer(), nullable=True),
        sa.Column("line_number_new", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["hunk_id"], ["hunk.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("line")
    op.drop_table("comment")
    op.drop_table("hunk")
    op.drop_table("diff")
    # ### end Alembic commands ###
