name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    concurrency:
      group: main
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv lock --check
      - run: uv sync --locked --all-extras --dev
      - run: uv run ruff check
      - run: uv run ruff format --check
      - run: uv run basedpyright
      - run: uv run pytest
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
